#!/usr/bin/env bash
# R20 QUANTUM TRADER - SAFE MODE QUICK REFERENCE
# Save as: quantum-trading/QUICK_START.sh

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  R20 QUANTUM TRADER - SAFE MODE - QUICK START                 ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Current directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

echo "📂 Working Directory: $SCRIPT_DIR"
echo ""

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}✗ Docker is not running${NC}"
    echo "Please start Docker Desktop and try again."
    exit 1
fi

echo -e "${GREEN}✓ Docker is running${NC}"
echo ""

# Menu
echo "═══════════════════════════════════════════════════════════════"
echo "QUICK COMMANDS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Build Docker Image"
echo "   $ docker compose -f docker-compose.safe.yml build"
echo ""
echo "2. Start in BACKTEST Mode (Safest - Default)"
echo "   $ docker compose -f docker-compose.safe.yml up"
echo ""
echo "3. Start in PAPER TRADING Mode (Demo API)"
echo "   $ docker compose -f docker-compose.safe.yml --profile paper up"
echo ""
echo "4. View Logs"
echo "   $ docker compose -f docker-compose.safe.yml logs -f"
echo ""
echo "5. View Trade Audit Log"
echo "   $ tail -f ./audit/trades.jsonl"
echo ""
echo "6. Stop Container"
echo "   $ docker compose -f docker-compose.safe.yml down"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "IMPORTANT FIRST STEPS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Copy safe environment:"
echo "   $ cp .env.safe .env"
echo ""
echo "2. CRITICAL - Change admin token in .env:"
echo "   $ sed -i 's/CHANGE_ME_TO_A_LONG_RANDOM_STRING_IMMEDIATELY/your_token_here/' .env"
echo ""
echo "3. Read complete guide:"
echo "   $ cat INTEGRATION_GUIDE.md"
echo ""
echo "4. Start backtest mode:"
echo "   $ docker compose -f docker-compose.safe.yml up"
echo ""
echo "5. Open dashboard:"
echo "   $ open http://localhost:8080"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "CONFIGURATION"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Edit .env for:"
echo "  TRADING_MODE       - backtest, paper, or live"
echo "  RISK_LIMIT_PERCENT - max risk per trade (1.0)"
echo "  STOP_LOSS_PERCENT  - auto-close if down (5.0)"
echo "  DRY_RUN            - simulate trades (1)"
echo "  R20_SETUP_TOKEN    - CHANGE IMMEDIATELY"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "SAFETY FEATURES"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✓ Backtest-first by default (no live API)"
echo "✓ Dry-run enabled (simulated trading)"
echo "✓ Risk limits enforced (cannot be exceeded)"
echo "✓ Strategy validation enabled"
echo "✓ Circuit breaker for errors"
echo "✓ Comprehensive audit logging"
echo "✓ Admin security (tokens, 2FA)"
echo "✓ Resource limits (2 CPU, 2GB memory)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "RECOMMENDED WORKFLOW"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Week 1-2:  BACKTEST (historical data)"
echo "Week 3-4:  PAPER TRADE (demo API, real-time)"
echo "Week 5+:   LIVE TRADING (only if results strong)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "MONITORING"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Logs:           ./logs/app.log"
echo "Trade Audit:    ./audit/trades.jsonl"
echo "API Audit:      ./audit/api.jsonl"
echo "Safety Checks:  ./audit/safety_check_*.json"
echo "Backups:        ./backups/"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "DASHBOARD"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "URL:   http://localhost:8080"
echo "Token: (from your .env R20_SETUP_TOKEN)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "HELP"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Documentation: ./INTEGRATION_GUIDE.md (READ THIS FIRST!)"
echo "Setup Guide:   ./SAFE_MODE_SETUP.md"
echo "Overview:      ./COMPLETE_SETUP.md"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo -e "${YELLOW}Next step: Read INTEGRATION_GUIDE.md${NC}"
echo ""
